apiVersion: v1
kind: Service
metadata:
  name: stock-monitor
  namespace: stock-monitor
  labels:
    app: stock-monitor
spec:
  type: NodePort
  selector:
    app: stock-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
